Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -39,7 +39,12 @@ jobs:
         unzip android.zip
         cd android
         chmod +x gradlew
-        ./gradlew assembleDebug -DCMAKE_VERBOSE_MAKEFILE=ON --info
+        ./gradlew assembleDebug || BUILD_FAILED=true
+        if [ "$BUILD_FAILED" = true ]; then
+          echo "=== MOSTRANDO REGISTROS DE ERROR DE CMAKE ==="
+          find app/.cxx -name "CMakeError.log" -exec cat {} +
+          exit 1
+        fi
 
     - name: Upload APK Artifact
       uses: actions/upload-artifact@v4
